export const pongGameOverMenuBackupNames = [
  'shaquille.oatmeal',
  'hanging_with_my_gnomies',
  'hoosier-daddy',
  'fast_and_the_curious',
  'averagestudent',
  'BadKarma',
  'google_was_my_idea',
  'cute.as.ducks',
  'casanova',
  'real_name_hidden',
  'HairyPoppins',
  'fedora_the_explorer',
  'OP_rah',
  'YellowSnowman',
  'JoeNotExotic',
]

export const pongGameOverMenuGameOverTitles = [
  'Nice Work!',
  'Way to Go!',
  'Awesome!',
  'Brilliant!',
  'Keep it Up!',
  'Impressive!',
  'Not Bad!',
  'Stellar!',
  'Amazing!',
  "You're a Rock Star!",
  'Out of This World!',
  'How About Another?',
  'A High Score?',
  'Did You Rock?',
]
